### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by F8ofnate** [dani69654/evm_scan_wallets#6]
Lifecycle scripts included in script_generatemnem_check_balance@1.0.0:
  start
    node index.js
  test
    echo "Error: no test specified" && exit 1

available via `npm run-script`:
  format
    prettier --write .

**Comment by dani69654** [comment]
Make sure to add useful info when you open an issue please.

**Comment by F8ofnate** [comment]
Ok I found what I was doing wrong and my apologies for not adding info. My new issue is im getting this error: 
No Sendgrid API key found. This function is disabled.
C:\Users\nate\Downloads\evm_scan_wallets-main\index.js:34
    throw new Error(error.message || error)
However, I created a .env file in the "evm_scan_wallets-main" folder and put:
  ETHEREUM_PRC_NODE =https://mainnet.infura.io/v3/(my key)
  SENDGRID_API_KEY =
what am I doing wrong?
