### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Piradoxlanieve** [dani69654/evm_scan_wallets#8]
Hi
** node -v
v10.19.0
**
**Description:    Ubuntu 20.04.3 LTS
**
I have tried with the infura rpc and my own with geth but I get this error, any ideas?
root@cyberpanel:~/evm_scan_wallets# npm start

> script_generatemnem_check_balance@1.0.0 start /root/evm_scan_wallets
> node index.js

/root/evm_scan_wallets/modules/web3Factory.js:7
  path = "m/44'/60'/0'/0/0"
       ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/evm_scan_wallets/index.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! script_generatemnem_check_balance@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the script_generatemnem_check_balance@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-15T20_57_22_726Z-debug.log

**Comment by Piradoxlanieve** [comment]
root@cyberpanel:~/evm_scan_wallets# cat /root/.npm/_logs/2021-12-15T21_10_10_427Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle script_generatemnem_check_balance@1.0.0~prestart: script_generatemnem_check_balance@1.0.0
6 info lifecycle script_generatemnem_check_balance@1.0.0~start: script_generatemnem_check_balance@1.0.0
7 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/evm_scan_wallets/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: CWD: /root/evm_scan_wallets
10 silly lifecycle script_generatemnem_check_balance@1.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle script_generatemnem_check_balance@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle script_generatemnem_check_balance@1.0.0~start: Failed to exec start script
13 verbose stack Error: script_generatemnem_check_balance@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid script_generatemnem_check_balance@1.0.0
15 verbose cwd /root/evm_scan_wallets
16 verbose Linux 5.11.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error script_generatemnem_check_balance@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the script_generatemnem_check_balance@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
root@cyberpanel:~/evm_scan_wallets#

**Comment by Piradoxlanieve** [comment]
root@cyberpanel:~/evm_scan_wallets# cat /root/.npm/_logs/2021-12-15T21_10_10_427Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle script_generatemnem_check_balance@1.0.0~prestart: script_generatemnem_check_balance@1.0.0
6 info lifecycle script_generatemnem_check_balance@1.0.0~start: script_generatemnem_check_balance@1.0.0
7 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/evm_scan_wallets/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle script_generatemnem_check_balance@1.0.0~start: CWD: /root/evm_scan_wallets
10 silly lifecycle script_generatemnem_check_balance@1.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle script_generatemnem_check_balance@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle script_generatemnem_check_balance@1.0.0~start: Failed to exec start script
13 verbose stack Error: script_generatemnem_check_balance@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid script_generatemnem_check_balance@1.0.0
15 verbose cwd /root/evm_scan_wallets
16 verbose Linux 5.11.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error script_generatemnem_check_balance@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the script_generatemnem_check_balance@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
root@cyberpanel:~/evm_scan_wallets#

**Comment by dani69654** [comment]
This issue has been resolved. 
Pull again and test.
