### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Handsomekaizer** [dani69654/evm_scan_wallets#9]
Hello great work and a great idea but somehow it does not seem to work. I hosted it on heroku and vercel but it won't work. Please can you upload it to heroku or any online site to see if it works. Please help me I really need this.

**Comment by dani69654** [comment]
What is the error you get?

**Comment by Handsomekaizer** [comment]
I get 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by Handsomekaizer** [comment]
Please host it on heroku and try please I really need this.
